### PR TITLE
ffi: Add rnp_key_export.

### PR DESCRIPTION
**Pull request by dewyatt**
I dropped the old partial export function and created a new one using the input/output concepts and such.

### CODE REVIEW

**Comment by ronaldtse** [comment]
@dewyatt there's still a "TODO" marked for the export of secret keys. Can we remove it now?

**Comment by dewyatt** [comment]
@ronaldtse 
> @dewyatt there's still a "TODO" marked for the export of secret keys. Can we remove it now?

I did remove the `/* TODO: export encrypted secret keys */` one, if that's what you mean.

Now that I look, I also removed `support export sec as pub` but that is not actually done, so I'll file an issue for that.

**Comment by dewyatt** [comment]
> LGTM, thanks, @dewyatt .
Now some conflicts should be resolved because of enarmor/dearmor merge.

Yeah I figured, will do.

> Also right now I'm working on ability to extract public key from secret/append signatures and userids, so then we would be able to extended key export with this functionality as well.

Yep I remember you mentioning that, that will be great to have!

**Comment by dewyatt** [comment]
Ok conflicts should be resolved. Also removed some old comment and fixed comment typos. I guess it makes sense to make sure CI passes again.

**Comment by dewyatt** [comment]
Ah nevermind, tricky rebase didn't go quite right...

**Comment by dewyatt** [comment]
I had to add a commit here as I saw something inconsistent when working on the ruby side. Not sure if you guys want to re-review or what.

**Comment by ronaldtse** [comment]
I'm happy with it, @ni4 feel free to merge when ready!

**Comment by ni4** [comment]
@dewyatt Hm, looks like I introduced new merge conflicts by merging other PRs.

**Comment by dewyatt** [comment]
No problem, resolved conflicts.

**Comment by ni4** [comment]
Thanks, @dewyatt .  Merging.

**Comment by dewyatt** [comment]
Thanks guys. I'm planning to do a PR for rnp release 0.10.0 today , and then do a ruby-rnp release too since I think some people are waiting on some features.

**Comment by ronaldtse** [comment]
Excellent! How close are we to a 1.0? :wink:

**Comment by dewyatt** [comment]
> Excellent! How close are we to a 1.0?

I only really did the minor bump because I removed a public function in the FFI here in this PR, so it made sense. (if we were not in 0.x, it would probably be a major bump).

Personally, I think a good time to release a 1.0 is when we can't think of any reason not to (123 open issues would be a good reason not to). That's my .02 anyways.

**Comment by ronaldtse** [comment]
That's true, but perhaps 1/5 out of the open issues are enhancement requests and/or stale issues. Let's try to get rid of those quick wins first. It would be a good time nonetheless to plan for a 1.0 release 😉

**Pull request merged**
