### PR TITLE
FFI: encrypt and sign

### PR DESCRIPTION
**Pull request by ni4**
This PR adds encrypt-and-sign functionality to FFI.
Also it reorganizes some internal functions for better code reuse.

### CODE REVIEW

**Comment by dewyatt** [comment]
* style comment: Maybe a bit excessive on the blank lines compared to the rest of the code base.
* small complaint: I'm a tad leery of expanded use of `rnp_ctx_t`. The way we use this in the lib really just seems to obfuscate function inputs. There have been a couple of times where I have set some field in `rnp_ctx_t` and passed it to a function, which didn't seem to work correctly, and I eventually realize the function doesn't even use that field of the structure.

Overall LGTM though.

**Comment by ronaldtse** [comment]
@ni4 please feel free to merge when ready. Thanks!

**Comment by ni4** [comment]
@ronaldtse @dewyatt Please see the updated PR. I removed extra empty lines and expanded documentation for rnp_ctx_t to have less confusion in future.

**Comment by ni4** [comment]
@ronaldtse Thanks, merging now.

**Pull request merged**
