### PR TITLE
Homedir fragmentation

### PR DESCRIPTION
**Pull request by catap**
Re-creating https://github.com/riboseinc/rnp/pull/81 because I haven't write access to https://github.com/shaunwheelhouse/rnp/tree/homedir-fragmentation and github doesn't allow to change target branch on pull request: https://github.com/isaacs/github/issues/18.

@ronaldtse it should merge well and you can close #81 without mergin.

### CODE REVIEW

**Comment by ronaldtse** [comment]
I believe @dewyatt is currently working on #81, perhaps this should merge to a separate branch instead of master? @dewyatt your preference?

**Comment by catap** [comment]
@ronaldtse it's all code from #81 but I just rebased it to current master, so it's mergin without errors as fast-forward.

**Comment by ronaldtse** [comment]
@catap indeed but #81 is actually incomplete. @dewyatt is currently completing it.

**Comment by catap** [comment]
@ronaldtse #81 can't merge and I think @dewyatt also hasn't got any write access to https://github.com/shaunwheelhouse/rnp/tree/homedir-fragmentation because it is inside fork of this repo.

So, I think he can push their new commit to this brnach, just rebase it to this root.

**Comment by catap** [comment]
Meanwhile, the build still broken :( but it can be merged

**Comment by dewyatt** [comment]
I'll try to get the tests passing before merging this. There are a few issues currently.

**Comment by shaunwheelhouse** [comment]
@dewyatt - at least one of those is likely due to the role of rnp_set_homedir() changing. It was previously responsible for concatenating (home, subdir) arguments together, and some of the tests rely on using it to set a complete path. This conflicts with the concatenation performed by the new keydir_* functions.

**Comment by dewyatt** [comment]
@shaunwheelhouse Thanks, I figured there might be something like that going on.

**Comment by catap** [comment]
@dewyatt do you have any ETA for fix it? Because I'm on #33 and looks like I will create a lot of conflict with this pull request

So, I think I should take a pause before you're fix it and merge it.

**Comment by dewyatt** [comment]
@catap It could take me a couple of days, I may have to fix up some other issues I'm seeing in the tests before this.

**Comment by catap** [comment]
@dewyatt thanks!

**Comment by dewyatt** [comment]
This kind of turned into a focus on the tests instead.

Quick summary of changes:

- Each test function now runs with its own temporary directory. $HOME will be set to this and the app will chdir to it as well. This is available in `*state`. This is to avoid potentially clobbering data when run locally. 
- I added a number of utility functions for the tests. Some require the last argument to be NULL, so do read the comments.
- I removed any large blocks of commented-out code in rnp_tests.c. If it doesn't work, it's probably better that we just don't commit it.
- Fixed a memory leak in rnp_end.

As for the homedir functionality, I haven't really done anything beyond Shaun's initial work.
I think we will want to add options for setting "subdir_gpg" and "subdir_ssh" to rnp/rnpkeys.
But I feel we should try to get this merged, and add a TODO for adding these additional options.

Right now, with these changes, everything should work as before, except the `homedir` should not include `.rnp` or `.ssh`.

**Comment by ronaldtse** [comment]
I've posted the remaining TODOs as #113. Thanks @dewyatt !

**Pull request merged**
