### PR TITLE
FFI WIP

### PR DESCRIPTION
**Pull request by dewyatt**
This is definitely a work-in-progress, and not intended to be merged.
This is what I came up with after rethinking some things.

(Note that I ripped out some functionality just to speed up the prototyping here and get things building+testing again.)

It's a bit less flexible than before but it's generally intentional.

I was thinking this and something similar to what I was doing in https://github.com/riboseinc/rnp/pull/482/files for enc/sig would be a decent API.

### CODE REVIEW

**Comment by dewyatt** [comment]
Also I did consider changing the key loading/saving interface to be more like:
```c
rnp_result_t rnp_load_keys_from_path(rnp_ffi_t ffi, const char *path);
rnp_result_t rnp_save_keys_to_path(rnp_ffi_t ffi, const char *pubpath, const char *secpath);
```

And letting the library internally sort them between the pub/sec rings. It's a bit more work though so I abandoned it for now.

**Comment by ronaldtse** [comment]
Any updates @dewyatt or should we merge this first?

**Comment by dewyatt** [comment]
I wouldn't merge it, I'm still actively working on it, I mostly just wanted to put this here for any feedback.

**Comment by ronaldtse** [comment]
@dewyatt any updates on the FFI? Thanks!

**Comment by dewyatt** [comment]
@ronaldtse Last week wasn't as productive as planned, but I'm making good progress so far this week. I'm just making some internal changes that should enable a less awkward FFI in some places right now.

**Comment by dewyatt** [comment]
@ronaldtse Despite delays, I think I've made some good progress on this. I'm aiming to finish decryption in the next 1-2 days and then continue this PR.

After that I think signing+verification remains. I'll probably have to settle for the old non-streaming API on that since I know ni4 is actively working on the streaming one.

**Comment by ronaldtse** [comment]
Thanks for the update @dewyatt . @ni4 perhaps could you let us know the status of streaming API work on signing/verification?

**Comment by dewyatt** [comment]
This still needs some work but probably worth merging as it's kind of intermediary.

Some doc comments need updates and some interfaces are likely to be improved. Things are still in flux a bit.

You can mostly get a good sense of the API by looking at the `test_ffi_encrypt_pass` test. I need to add a test for mixed pk+pass encryption as well.

Still need to add signing/verification as well, and will target the new streaming API when that is ready.

**Comment by catap** [comment]
I agree with @ronaldtse that better to merge it now ;)

**Pull request merged**
