### PR TITLE
Changed pgp_add_time to use enum instead of char* parameter.

### LINKED ISSUE #219: pgp_add_time needs some refactoring
It's a bit weird - it has char* parameter type, which can be "birth" or "expiration", and then it is mapped to `tag = (strcmp(type, "birth") == 0) ? PGP_PTAG_SS_CREATION_TIME : PGP_PTAG_SS_EXPIRATION_TIME`

I think char* parameter should be replaced to some enum or directly to the `PGP_PTAG_SS_CREATION_TIME/PGP_PTAG_SS_EXPIRATION_TIME`

### PR DESCRIPTION
**Pull request by ni4**
Fixes #219 , mostly for better code readability.

### CODE REVIEW

**Comment by flowher** [comment]
LGTM

**Comment by ni4** [comment]
What policy do we have? May I merge it now, or wait for @dewyatt approval as well?

**Comment by dewyatt** [comment]
@ronaldtse Do you want to formalize a PR review process (see @ni4 comment above)? For example, require 2 approvals on each PR, or something like that (you can enforce a policy via github too, of course).

**Comment by ni4** [comment]
Thanks! Yeah, possibly it would be easier/more organized to have some simple formal rules, like naming of the branches, number of approves needed for the merge and so on.

**Comment by ronaldtse** [comment]
Yes @dewyatt let's formalize a policy to require two approvals to merge, and the other typical rules we should follow, could you help add them to the Dev Guide?

**Pull request merged**
