### PR TITLE
Adds support for SHA3/256 and SHA3/512

### PR DESCRIPTION
**Pull request by henrydcase**

### CODE REVIEW

**Comment by henrydcase** [comment]
Build fails because "main.cpp:40:19: fatal error: QWindow: No such file or directory" (wait, what!?)

**Comment by dewyatt** [comment]
> Build fails because "main.cpp:40:19: fatal error: QWindow: No such file or directory" (wait, what!?)

haha yeah, fixed in #642. It's trying to build pinentry with Qt4.

**Comment by henrydcase** [comment]
Good that's fixed :)

**Comment by henrydcase** [comment]
Great, thanks for checking that.

**Comment by ni4** [comment]
@henrydcase  I merged #642, so feel free to merge this one

**Pull request merged**
