### PR TITLE
FFI: add rnp_key_get_primary_grip() function.

### PR DESCRIPTION
**Pull request by ni4**
We didn't have a way to find primary key from subkey, so here it is.

### CODE REVIEW

**Comment by ronaldtse** [comment]
@ni4 there are some merge conflicts -- could you please help resolve+merge them? Thanks!

**Comment by ni4** [comment]
@ronaldtse Sure, rebased. Will wait for Travis and then merge.

**Comment by dewyatt** [comment]
I think I rebased this when it didn't need it, sorry. :P

**Comment by ni4** [comment]
@dewyatt No problem, still need to wait for Travis in #865

**Pull request merged**
