### PR TITLE
Add GPG 2.1 to CI and run cli_tests.py

### PR DESCRIPTION
**Pull request by dewyatt**
Fixes https://github.com/riboseinc/rnp/issues/394#issuecomment-323879018

I also realized my mistake of setting CORES based on /proc/cpuinfo in Travis CI. The container's /proc/cpuinfo matches the host, of course, so sometimes we were trying to build botan and other things with 32 cores in a travis-ci container (which resulted in processes being killed). Now defaults to 2 cores and can be overridden.

### CODE REVIEW

**Comment by ronaldtse** [comment]
@dewyatt could we use a separate build directory that gets removed after the CI run than just `~/builds`?

The runs on Jenkins reuses this directory across separate jobs and I right now I have to specify `rm` after runs.

**Comment by ronaldtse** [comment]
Or at least extract that path and make it configurable through ENV. Thanks!

**Comment by dewyatt** [comment]
@ronaldtse Sure thing.

@ni4 Ideas on the failure here?: https://travis-ci.org/riboseinc/rnp/jobs/267022584

**Comment by dewyatt** [comment]
@ronaldtse Not sure if I completely addressed your issue there. I see the jenkins build failed?

**Comment by ronaldtse** [comment]
I've attempted a fix, could you push something again to trigger it?

**Comment by dewyatt** [comment]
Not sure why but `cli_tests.py` seems to randomly fail on removing some temporary directory.
Might just need to add `ignore_errors=True`, but would be nice to know the underlying cause.

(I think we can just close & reopen to trigger build again)

**Comment by dewyatt** [comment]
Oh right that won't work for Jenkins. Ok one sec.

**Comment by ronaldtse** [comment]
Thanks, that should work - it's polling every minute so you might need to wait for half more minute...

**Comment by ronaldtse** [comment]
@dewyatt it ran but failed here:
```sh
Running in /tmp/tmpdOFCAx
Cannot find utility gpg. Exiting.
```

We need to manually point to the `gpg` executable since it's specified inside `$LOCAL_BUILDS`? It looks like it works on Travis...

**Comment by ronaldtse** [comment]
Ah it failed much earlier. There's a line to call `gpg` to import the key but there's no gpg installed in the build machine. Will fix this.

**Comment by dewyatt** [comment]
@ni4 It looks like there's a race condition where gpg-agent sometimes leaves a root-owned socket in the temporary directory used for the tests. I think the best thing to do is to rework `cli_tests.py` so that each test gets its own directory (or a group of tests) and then it's safer to have `ignore_errors=True` when purging things. Thoughts?

**Comment by ronaldtse** [comment]
Yay! Jenkins works!

```sh
Run 143 tests, 143 succeeded and 0 failed.
```

**Comment by ronaldtse** [comment]
@dewyatt @ni4 yes indeed, running GnuPG in quick succession will cause lingering sockets which can be solved with separating the `.gpg` home directories which is what we do currently. Thus the need for rnp.

**Comment by ronaldtse** [comment]
@ni4 this is passing now, could you approve / merge? Thanks!

**Comment by ni4** [comment]
@dewyatt @ronaldtse Ok, I'll update script to not fail in clear_keyrings within the next PR 
Also I'm thinking about updating it with some more logging.

**Pull request merged**
