### PR TITLE
Don't try to execute regex from NULL memory

### PR DESCRIPTION
**Pull request by catap**
Small bugfix for https://github.com/riboseinc/rnp/issues/88

### CODE REVIEW

**Comment by dewyatt** [comment]
Can you also add a check to rnpkeys.c to print an error and exit early if `f==NULL`:
https://github.com/riboseinc/rnp/blob/c40152e4c6554ea54158f20f4e1d04aadae409b1/src/rnpkeys/rnpkeys.c#L230

**Comment by catap** [comment]
@dewyatt, it prints the error:
```
➜  rnp git:(not_crash_at_import_key_without_option) ✗ ./src/rnpkeys/rnpkeys --import-key                     
rnp: warning - cannot turn off core dumps
rnp: warning: core dumps enabled, sensitive data may be leaked to disk
Bad address
cannot import key from file (null)
➜  rnp git:(not_crash_at_import_key_without_option) ✗ 
```

**Comment by catap** [comment]
But, I think you're right. The safe way is check that it is NULL, because printf's behaviour on NULL string isn't specified.

**Comment by dewyatt** [comment]
I went ahead and merged this since it definitely looks good to me, and I think @ronaldtse is probably busy!

**Comment by ronaldtse** [comment]
Thank you @catap for the changes and thanks to @dewyatt for the merge!

**Pull request merged**
