### PR TITLE
Performance improvements

### PR DESCRIPTION
**Pull request by ni4**
This PR fixes some performance bottlenecks in RNP:
- adds table-based crc-24 calculation to armouring/dearmoring streams
- fixes slow cfb encryption/decryption
- adds caching to stream writes
- updates performance tests

Within this changes for main encryption algorithms (AES, Camellia) RNP is 1.7-2 times faster then GnuPG (on my machine). Some ciphers, like Blowfish, Cast5 are slower. I didn't dig deep, but it seems that for those Botan has slower implementation then for AES/Camellia. @randombit, what do you think?

Most likely there are more things which may be improved. With these changes performance was improved in 1.5-2.0 times.

The results are as following:
```
#1. Small file symmetric encryption
ENCRYPT-SMALL-BINARY:RNP:26.22 runs/sec
ENCRYPT-SMALL-BINARY:GPG:39.44 runs/sec
ENCRYPT-SMALL-BINARY:RNP vs GPG:1.50
ENCRYPT-SMALL-ARMOUR:RNP:25.43 runs/sec
ENCRYPT-SMALL-ARMOUR:GPG:40.06 runs/sec
ENCRYPT-SMALL-ARMOUR:RNP vs GPG:1.58
#2. Large file symmetric encryption
ENCRYPT-AES128-BINARY:RNP:154.76 MB/sec
ENCRYPT-AES128-BINARY:GPG:70.71 MB/sec
ENCRYPT-AES128-BINARY:RNP vs GPG:0.46
ENCRYPT-AES192-BINARY:RNP:125.19 MB/sec
ENCRYPT-AES192-BINARY:GPG:62.10 MB/sec
ENCRYPT-AES192-BINARY:RNP vs GPG:0.50
ENCRYPT-AES256-BINARY:RNP:144.64 MB/sec
ENCRYPT-AES256-BINARY:GPG:71.48 MB/sec
ENCRYPT-AES256-BINARY:RNP vs GPG:0.49
ENCRYPT-TWOFISH-BINARY:RNP:86.25 MB/sec
ENCRYPT-TWOFISH-BINARY:GPG:52.35 MB/sec
ENCRYPT-TWOFISH-BINARY:RNP vs GPG:0.61
ENCRYPT-BLOWFISH-BINARY:RNP:59.89 MB/sec
ENCRYPT-BLOWFISH-BINARY:GPG:75.72 MB/sec
ENCRYPT-BLOWFISH-BINARY:RNP vs GPG:1.26
ENCRYPT-CAST5-BINARY:RNP:58.39 MB/sec
ENCRYPT-CAST5-BINARY:GPG:69.47 MB/sec
ENCRYPT-CAST5-BINARY:RNP vs GPG:1.19
ENCRYPT-CAMELLIA128-BINARY:RNP:83.33 MB/sec
ENCRYPT-CAMELLIA128-BINARY:GPG:50.05 MB/sec
ENCRYPT-CAMELLIA128-BINARY:RNP vs GPG:0.60
ENCRYPT-CAMELLIA192-BINARY:RNP:68.03 MB/sec
ENCRYPT-CAMELLIA192-BINARY:GPG:42.69 MB/sec
ENCRYPT-CAMELLIA192-BINARY:RNP vs GPG:0.63
ENCRYPT-CAMELLIA256-BINARY:RNP:70.08 MB/sec
ENCRYPT-CAMELLIA256-BINARY:GPG:44.24 MB/sec
ENCRYPT-CAMELLIA256-BINARY:RNP vs GPG:0.63
#3. Large file armoured encryption
ENCRYPT-LARGE-ARMOUR:RNP:64.93 MB/sec
ENCRYPT-LARGE-ARMOUR:GPG:43.85 MB/sec
ENCRYPT-LARGE-ARMOUR:RNP vs GPG:0.68
```

### CODE REVIEW

**Comment by ronaldtse** [comment]
@ni4 this is impressive stuff.

For the CLI test output multiple, could we write "XX% faster" or "XX% slower" rather than "0.63"

I assume the `ENCRYPT_{SMALL,LARGE}_` tests are all using AES CFB? I wonder why `rnp` is so much slower with small files when it's so much faster with large ones.

It feels either something to do with the stream setup or memory allocation (and/or the finalization of it). Maybe if we can graph out memory allocation comparison we can find out why.

**Comment by flowher** [comment]
Does your gnupg support hardware instructions?

**Comment by randombit** [comment]
Looks good to me though I didn't read the stream cache logic too carefully.

One thing, did you try seeing what gcc/clang do if you just use `uint64_t` everywhere for the CFB code? I would think GCC would know how to convert this into a pair of 32-bit registers with basically no extra overhead. Which would simplify the code a little bit.

BTW, some caution here, I did something very much like what you did for CFB XOR at one point in Botan and ran into problems because GCC -O3 will vectorize the XORs. The problem is that when GCC vectorized it, it used aligned SSE loads (even though you can normally do misaligned loads on x86 just fine), so the code would crash if fed a misaligned buffer. Maybe this is fixed in recent GCC, don't know.

Re Blowfish and CAST perf, I'm not sure why these would be particularly slower than what libgcrypt is doing... however did a little digging and checked on asm dumps, for CAST I see GCC is doing something kind of non-optimal, because we have to be careful to avoid undefined behavior in the bit rotation function, but GCC misses the fact that one of our operations is redundant. This caused ~15% slowdown (in the overall CAST-128 encryption) vs just doing the "naive" rotation instrinsic. I filed a bug with GCC https://gcc.gnu.org/bugzilla/show_bug.cgi?id=82498. I briefly played around with trying to get something that both avoids undefined behavior and gets GCC to generate decent code but no luck so far.

Actually also it appears Clang generates terrible code for `rotate_left` in Botan, doesn't even generate the `roll` instruction instead does shift/shift/or :(

**Comment by randombit** [comment]
Re the performance of CAST-128 I improved things ~20% by using asm for the rotation - https://github.com/randombit/botan/pull/1247

Don't know how that will affect the overall rnp performance but it's something.

**Comment by ni4** [comment]
@flowher Reasonable comment, thanks. I used older GnuPG installation with libgcrypt 1.7.7. Now I updated it to 1.8.1 and speeds are comparable to RNP - 150Mb/sec for AES. However, homebrew formula is built with '--disable-asm'. Will investigate it a little bit more.

@ronaldtse Sure, I'll update output of the performance test for better readability, it is awkward now.

**Comment by ni4** [comment]
@randombit Thanks for the detailed comment. Sure, will update to not use #ifdefs, just uint64_t. Also got warnings about unaligned 64-bit pointer access, will investigate it. As I quick-read yesterday unaligned access may slow the things down twice. So needs some more investigation.

**Comment by flowher** [comment]
>  Also got warnings about unaligned 64-bit pointer access, will investigate it
Problems, problems, problems. I've been there and wasted a lot of time debugging. Better fix it before commit

**Comment by ni4** [comment]
@ronaldtse I updated the output format, please see numbers for GnuPG with libgcrypt 1.8.1 below
Also rebased/removed #ifdefs as @randombit suggested.

Will investigate slowdown on runs/sec and problems with unaligned memory access later today.

```
#1. Small file symmetric encryption
ENCRYPT-SMALL-BINARY          : RNP is  55% SLOWER then GnuPG (28.01 runs/sec vs 61.70 runs/sec)
ENCRYPT-SMALL-ARMOUR          : RNP is  54% SLOWER then GnuPG (28.23 runs/sec vs 61.36 runs/sec)
#2. Large file symmetric encryption
ENCRYPT-AES128-BINARY         : RNP is   3% SLOWER then GnuPG (170.28 MB/sec vs 175.38 MB/sec)
ENCRYPT-AES192-BINARY         : RNP is   1% SLOWER then GnuPG (166.55 MB/sec vs 169.05 MB/sec)
ENCRYPT-AES256-BINARY         : RNP is   1% SLOWER then GnuPG (156.39 MB/sec vs 158.44 MB/sec)
ENCRYPT-TWOFISH-BINARY        : RNP is   2% SLOWER then GnuPG (89.61 MB/sec vs 91.19 MB/sec)
ENCRYPT-BLOWFISH-BINARY       : RNP is  20% SLOWER then GnuPG (59.27 MB/sec vs 74.32 MB/sec)
ENCRYPT-CAST5-BINARY          : RNP is  18% SLOWER then GnuPG (59.71 MB/sec vs 72.48 MB/sec)
ENCRYPT-CAMELLIA128-BINARY    : RNP is   7% FASTER then GnuPG (87.01 MB/sec vs 81.63 MB/sec)
ENCRYPT-CAMELLIA192-BINARY    : RNP is   6% FASTER then GnuPG (73.04 MB/sec vs 68.67 MB/sec)
ENCRYPT-CAMELLIA256-BINARY    : RNP is   8% FASTER then GnuPG (74.05 MB/sec vs 68.37 MB/sec)
#3. Large file armoured encryption
ENCRYPT-LARGE-ARMOUR          : RNP is   8% FASTER then GnuPG (68.75 MB/sec vs 63.77 MB/sec)
```

**Comment by ronaldtse** [comment]
@ni4 somehow Travis is still failing on this build. Looks good to merge once this is fixed!

PS. I wonder about the differences between this run and @flowher 's run in #492 ?

**Comment by ni4** [comment]
@ronaldtse Build fails because of the alignment error in sanitize run: `SUMMARY: AddressSanitizer: undefined-behavior symmetric.c:307:17 in 
symmetric.c:309:23: runtime error: load of misaligned address 0x62d000000416 for type 'uint64_t' (aka 'unsigned long'), which requires 8 byte alignment`. 

So, trying to find a good way to overcome this.

**Comment by ronaldtse** [comment]
@randombit @dewyatt @flowher any quick solutions to the alignment issue? Would like to merge this ASAP. Thanks!

**Comment by ni4** [comment]
@ronaldtse I only found a way to use memcpy to temporary aligned buffer, if parameters are misaligned. And make cache in encrypted stream, which is used most times, aligned. Will finish these changes today or tomorrow.

**Comment by ronaldtse** [comment]
@ni4 nice! Look forward to merging this 👍

**Comment by ronaldtse** [comment]
@dewyatt @flowher we could merge this? Thanks!

**Comment by ni4** [comment]
@ronaldtse Alignment issue is now fixed. I will further investigate why we are so slow on small files, and check tests. Currently encryption itself doesnt' take much time, according to profiler. See the attached screenshot:

screen shot 2017-10-14 at 1 50 38 pm

**Comment by ni4** [comment]
@randombit Btw, why spending in botan_block_cipher_encrypt_blocks around 1.10s, only 600ms are spent inside of AES encryption itself?

**Comment by ronaldtse** [comment]
Any further comments or can we merge this first?

**Comment by flowher** [comment]
I think I'm OK. Let me satar at it few mins more.

**Comment by ni4** [comment]
@flowher @ronaldtse  I updated PR with performance tests for decryption, it appears that GnuPG is much slower in decryption as in encryption. Also strangely rnp is faster in decryption:
```
#1. Small file symmetric encryption
ENCRYPT-SMALL-BINARY          : RNP is  53% SLOWER then GnuPG (26.11 runs/sec vs 56.06 runs/sec)
ENCRYPT-SMALL-ARMOUR          : RNP is  54% SLOWER then GnuPG (26.00 runs/sec vs 57.05 runs/sec)
#2. Large file symmetric encryption
ENCRYPT-AES128-BINARY         : RNP is  12% SLOWER then GnuPG (148.01 MB/sec vs 167.98 MB/sec)
ENCRYPT-AES192-BINARY         : RNP is   1% SLOWER then GnuPG (153.13 MB/sec vs 154.77 MB/sec)
ENCRYPT-AES256-BINARY         : RNP is   1% SLOWER then GnuPG (143.57 MB/sec vs 144.58 MB/sec)
ENCRYPT-TWOFISH-BINARY        : RNP is   3% SLOWER then GnuPG (85.40 MB/sec vs 88.06 MB/sec)
ENCRYPT-BLOWFISH-BINARY       : RNP is  22% SLOWER then GnuPG (59.09 MB/sec vs 75.97 MB/sec)
ENCRYPT-CAST5-BINARY          : RNP is  27% SLOWER then GnuPG (54.75 MB/sec vs 75.48 MB/sec)
ENCRYPT-CAMELLIA128-BINARY    : RNP is   3% FASTER then GnuPG (81.71 MB/sec vs 79.30 MB/sec)
ENCRYPT-CAMELLIA192-BINARY    : RNP is   8% FASTER then GnuPG (72.48 MB/sec vs 67.32 MB/sec)
ENCRYPT-CAMELLIA256-BINARY    : RNP is   5% FASTER then GnuPG (70.39 MB/sec vs 67.29 MB/sec)
#3. Large file armoured encryption
ENCRYPT-LARGE-ARMOUR          : RNP is   3% FASTER then GnuPG (66.40 MB/sec vs 64.32 MB/sec)
#4. Small file symmetric decryption
DECRYPT-SMALL-BINARY          : RNP is  54% SLOWER then GnuPG (26.29 runs/sec vs 57.08 runs/sec)
DECRYPT-SMALL-ARMOUR          : RNP is  52% SLOWER then GnuPG (27.44 runs/sec vs 56.70 runs/sec)
#5. Large file symmetric decryption
DECRYPT-AES128-BINARY         : RNP is 125% FASTER then GnuPG (176.41 MB/sec vs 78.52 MB/sec)
DECRYPT-AES192-BINARY         : RNP is 133% FASTER then GnuPG (173.26 MB/sec vs 74.31 MB/sec)
DECRYPT-AES256-BINARY         : RNP is 107% FASTER then GnuPG (158.03 MB/sec vs 76.19 MB/sec)
DECRYPT-TWOFISH-BINARY        : RNP is  76% FASTER then GnuPG (89.20 MB/sec vs 50.75 MB/sec)
DECRYPT-BLOWFISH-BINARY       : RNP is  39% FASTER then GnuPG (67.63 MB/sec vs 48.72 MB/sec)
DECRYPT-CAST5-BINARY          : RNP is  48% FASTER then GnuPG (65.68 MB/sec vs 44.35 MB/sec)
DECRYPT-CAMELLIA128-BINARY    : RNP is  83% FASTER then GnuPG (86.41 MB/sec vs 47.13 MB/sec)
DECRYPT-CAMELLIA192-BINARY    : RNP is  78% FASTER then GnuPG (72.73 MB/sec vs 40.87 MB/sec)
DECRYPT-CAMELLIA256-BINARY    : RNP is  75% FASTER then GnuPG (71.67 MB/sec vs 40.90 MB/sec)
#6. Large file armoured decryption
DECRYPT-LARGE-ARMOUR          : RNP is  57% FASTER then GnuPG (51.56 MB/sec vs 32.83 MB/sec)
```

**Comment by ronaldtse** [comment]
@ni4 for the latest benchmarks are we already enabling all the hardware acceleration for GnuPG, as seen in @flowher 's #492 ?

**Comment by flowher** [comment]
This is mine comparision:

```
#1. Small file symmetric encryption
ENCRYPT-SMALL-BINARY          : RNP is  75% SLOWER then GnuPG (40.88 runs/sec vs 165.10 runs/sec)
ENCRYPT-SMALL-ARMOUR          : RNP is  77% SLOWER then GnuPG (42.84 runs/sec vs 185.67 runs/sec)
#2. Large file symmetric encryption
ENCRYPT-AES128-BINARY         : RNP is  30% SLOWER then GnuPG (192.36 MB/sec vs 274.11 MB/sec)
ENCRYPT-AES192-BINARY         : RNP is  27% SLOWER then GnuPG (184.22 MB/sec vs 251.78 MB/sec)
ENCRYPT-AES256-BINARY         : RNP is  28% SLOWER then GnuPG (172.63 MB/sec vs 238.76 MB/sec)
ENCRYPT-TWOFISH-BINARY        : RNP is  16% SLOWER then GnuPG (103.71 MB/sec vs 124.18 MB/sec)
ENCRYPT-BLOWFISH-BINARY       : RNP is  19% SLOWER then GnuPG (77.24 MB/sec vs 95.26 MB/sec)
ENCRYPT-CAST5-BINARY          : RNP is  19% SLOWER then GnuPG (71.18 MB/sec vs 87.34 MB/sec)
ENCRYPT-CAMELLIA128-BINARY    : RNP is  23% SLOWER then GnuPG (83.55 MB/sec vs 107.86 MB/sec)
ENCRYPT-CAMELLIA192-BINARY    : RNP is  18% SLOWER then GnuPG (70.11 MB/sec vs 85.31 MB/sec)
ENCRYPT-CAMELLIA256-BINARY    : RNP is  19% SLOWER then GnuPG (70.62 MB/sec vs 87.46 MB/sec)
#3. Large file armoured encryption
ENCRYPT-LARGE-ARMOUR          : RNP is  14% FASTER then GnuPG (101.72 MB/sec vs 88.99 MB/sec)
#4. Small file symmetric decryption
DECRYPT-SMALL-BINARY          : RNP is  75% SLOWER then GnuPG (50.14 runs/sec vs 199.93 runs/sec)
DECRYPT-SMALL-ARMOUR          : RNP is  75% SLOWER then GnuPG (49.83 runs/sec vs 197.94 runs/sec)
#5. Large file symmetric decryption
DECRYPT-AES128-BINARY         : RNP is 120% FASTER then GnuPG (258.00 MB/sec vs 117.42 MB/sec)
DECRYPT-AES192-BINARY         : RNP is 116% FASTER then GnuPG (237.69 MB/sec vs 109.84 MB/sec)
DECRYPT-AES256-BINARY         : RNP is 103% FASTER then GnuPG (240.62 MB/sec vs 118.54 MB/sec)
DECRYPT-TWOFISH-BINARY        : RNP is  26% FASTER then GnuPG (106.82 MB/sec vs 84.86 MB/sec)
DECRYPT-BLOWFISH-BINARY       : RNP is   0% SLOWER then GnuPG (104.18 MB/sec vs 104.55 MB/sec)
DECRYPT-CAST5-BINARY          : RNP is   4% SLOWER then GnuPG (94.32 MB/sec vs 98.17 MB/sec)
DECRYPT-CAMELLIA128-BINARY    : RNP is  19% SLOWER then GnuPG (85.27 MB/sec vs 104.88 MB/sec)
DECRYPT-CAMELLIA192-BINARY    : RNP is  28% SLOWER then GnuPG (72.44 MB/sec vs 101.13 MB/sec)
DECRYPT-CAMELLIA256-BINARY    : RNP is  29% SLOWER then GnuPG (71.78 MB/sec vs 100.47 MB/sec)
#6. Large file armoured decryption
DECRYPT-LARGE-ARMOUR          : RNP is 140% FASTER then GnuPG (116.41 MB/sec vs 48.59 MB/sec)
```

With following configuration:

```
rnp@642fda2623a632eb0285a21a84558b305b82f4c7
flags: -DHAVE_CONFIG_H -Werror -Wall -Wpointer-arith -Wmissing-declarations -Wmissing-prototypes -O3 -std=c11 -D_GNU_SOURCE  -MD -MP -MF -fPIC -DPIC

botan@d52dece3876df6d19681fb16cb607325aee01052
flags: -fstack-protector -m64 -pthread -std=c++11 -D_REENTRANT -O3 -momit-leaf-frame-pointer -Wall -Wextra -Wpedantic -Wstrict-aliasing -Wstrict-overflow=5 -Wcast-align -Wmissing-declarations -Wpointer-arith -Wcast-qual -Wzero-as-null-pointer-constant -Wnon-virtual-dtor

gnupg@1ed21eee79749b976b4a935f2279b162634e9c5e
flags: -g -O2 -MT libcommon_a-agent-opt.o -MD -MP -MF

**Comment by ni4** [comment]
@flowher I used homebrew for libgcrypt/gnupg installation, however after rebuilding from sources see the following:
```
        Libgcrypt v1.8.1 has been configured as follows:
         
        Platform:                  Darwin (x86_64-apple-darwin16.7.0)
        Hardware detection module: hwf-x86
        Enabled cipher algorithms: arcfour blowfish cast5 des aes twofish
                                   serpent rfc2268 seed camellia idea salsa20
                                   gost28147 chacha20
        Enabled digest algorithms: crc gostr3411-94 md4 md5 rmd160 sha1
                                   sha256 sha512 sha3 tiger whirlpool stribog
                                   blake2
        Enabled kdf algorithms:    s2k pkdf2 scrypt
        Enabled pubkey algorithms: dsa elgamal rsa ecc
        Random number generator:   default
        Try using jitter entropy:  no
        Using linux capabilities:  no
        Try using Padlock crypto:  yes
        Try using AES-NI crypto:   yes
        Try using Intel PCLMUL:    yes
        Try using Intel SSE4.1:    yes
        Try using DRNG (RDRAND):   yes
        Try using Intel AVX:       yes
        Try using Intel AVX2:      yes
        Try using ARM NEON:        n/a
        Try using ARMv8 crypto:    n/a
```

GnuPG build options: `-Wall -Wno-pointer-sign -Wpointer-arith  -g -O2`, compiler - `clang`

**Comment by ronaldtse** [comment]
Seems the only libgcrypt configuration differences are:
```
        Try using jitter entropy:  no
        Using linux capabilities:  no
```

Maybe this is the performance difference mainly due to @ni4 's macOS and @flowher 's Linux?

**Comment by flowher** [comment]
This and I'm was using gcc.

Just for reference, I've recompiled GnuPG, so that it doesn't use jitter for entropy and doesn't use linux capabilities and everything is compiled with clang (4.0.0)

```
Setting up test in /tmp/rnpptmpRe6vgh ...
Generating large file of size 100.0MB
#1. Small file symmetric encryption
ENCRYPT-SMALL-BINARY          : RNP is  81% SLOWER then GnuPG (45.79 runs/sec vs 240.95 runs/sec)
ENCRYPT-SMALL-ARMOUR          : RNP is  80% SLOWER then GnuPG (47.85 runs/sec vs 241.34 runs/sec)
#2. Large file symmetric encryption
ENCRYPT-AES128-BINARY         : RNP is  24% SLOWER then GnuPG (220.58 MB/sec vs 290.98 MB/sec)
ENCRYPT-AES192-BINARY         : RNP is  18% SLOWER then GnuPG (214.96 MB/sec vs 263.35 MB/sec)
ENCRYPT-AES256-BINARY         : RNP is  18% SLOWER then GnuPG (199.90 MB/sec vs 242.55 MB/sec)
ENCRYPT-TWOFISH-BINARY        : RNP is  13% SLOWER then GnuPG (111.17 MB/sec vs 127.25 MB/sec)
ENCRYPT-BLOWFISH-BINARY       : RNP is  20% SLOWER then GnuPG (76.16 MB/sec vs 94.80 MB/sec)
ENCRYPT-CAST5-BINARY          : RNP is  16% SLOWER then GnuPG (73.78 MB/sec vs 88.35 MB/sec)
ENCRYPT-CAMELLIA128-BINARY    : RNP is  20% SLOWER then GnuPG (80.83 MB/sec vs 101.43 MB/sec)
ENCRYPT-CAMELLIA192-BINARY    : RNP is  20% SLOWER then GnuPG (67.52 MB/sec vs 84.09 MB/sec)
ENCRYPT-CAMELLIA256-BINARY    : RNP is  18% SLOWER then GnuPG (67.49 MB/sec vs 82.42 MB/sec)
#3. Large file armoured encryption
ENCRYPT-LARGE-ARMOUR          : RNP is  42% FASTER then GnuPG (122.29 MB/sec vs 86.09 MB/sec)
#4. Small file symmetric decryption
DECRYPT-SMALL-BINARY          : RNP is  79% SLOWER then GnuPG (51.66 runs/sec vs 244.66 runs/sec)
DECRYPT-SMALL-ARMOUR          : RNP is  78% SLOWER then GnuPG (52.28 runs/sec vs 234.53 runs/sec)
#5. Large file symmetric decryption
DECRYPT-AES128-BINARY         : RNP is 159% FASTER then GnuPG (308.30 MB/sec vs 119.04 MB/sec)
DECRYPT-AES192-BINARY         : RNP is 159% FASTER then GnuPG (298.13 MB/sec vs 115.03 MB/sec)
DECRYPT-AES256-BINARY         : RNP is 134% FASTER then GnuPG (272.98 MB/sec vs 116.88 MB/sec)
DECRYPT-TWOFISH-BINARY        : RNP is  36% FASTER then GnuPG (112.58 MB/sec vs 82.61 MB/sec)
DECRYPT-BLOWFISH-BINARY       : RNP is   4% FASTER then GnuPG (103.94 MB/sec vs 100.18 MB/sec)
DECRYPT-CAST5-BINARY          : RNP is   1% FASTER then GnuPG (95.02 MB/sec vs 94.14 MB/sec)
DECRYPT-CAMELLIA128-BINARY    : RNP is  17% SLOWER then GnuPG (84.49 MB/sec vs 101.23 MB/sec)
DECRYPT-CAMELLIA192-BINARY    : RNP is  30% SLOWER then GnuPG (68.15 MB/sec vs 97.13 MB/sec)
DECRYPT-CAMELLIA256-BINARY    : RNP is  27% SLOWER then GnuPG (69.99 MB/sec vs 96.38 MB/sec)
#6. Large file armoured decryption
DECRYPT-LARGE-ARMOUR          : RNP is 199% FASTER then GnuPG (126.29 MB/sec vs 42.24 MB/sec)
```

**Comment by ni4** [comment]
@ronaldtse @flowher  I wonder whether it could be a problem in cli_perf.py. I already found one issue, which makes some impact on time measurement. However I still get the approximately same results as before. Also running rnp for small files separately from the command line takes the same 15-20ms as gpg. So, investigating...

**Comment by ronaldtse** [comment]
@flowher somehow in your latest tests both implementations became faster in most cases...

Maybe it's something to do with the ordering/dependencies of the tests run?

**Comment by flowher** [comment]
Yes, I've noticed. Dependencies were the same. I've recompiled libgcrypt, gnupg, rnp and botan in ``clang`` and I think it produces faster code.

**Comment by ni4** [comment]
@flowher If you have some minutes - does the code from the commit 07b8bf8 make any impact on the numbers?

**Comment by ni4** [comment]
After playing some more time with I have the following suggestions:
- Python process spawning code takes some time, and strangely it is not on our side. Running rnp/gpg from shell, in 1000 iterations, gives the following result:
```sh
$ time ./rnp_test.sh 
real	0m13.461s
user	0m6.182s
sys	0m4.292s
$ time ./gpg_test.sh
real	0m13.217s
user	0m6.865s
sys	0m3.623s
```
- speed definitely depends on CPU and drive speed, and depending on the combination results may vary. On my system creation of 100mb file with mkfile takes ~0.3-0.5s. cat'ing it do /dev/null - ~0.1-0.2s. So, from overall processing time of 100Mb file around 1s (~100Mb/sec) around half is spent for writing and reading.
- speed should also depend on drive caching and so on

**Comment by ronaldtse** [comment]
@ni4 I think we should produce a static trace per command execution, something like:
```csv
(pid),(thread-id),(vmem),(realmem),(readspeed)(writespeed),(cpu%),...
```

Such as using `pidstat` (on Linux). 

Or much more serious like [http://www.brendangregg.com/perf.html](`perf`)?

**Comment by flowher** [comment]
I've run ```bad50667fd1ba20390c345d71fa97d05652b0bb5```, those are results (havn't analyse them yet)

```
Setting up test in /tmp/rnpptmpnw3Mv_ ...
Generating large file of size 100.0MB
#1. Small file symmetric encryption
ENCRYPT-SMALL-BINARY          : RNP is  80% SLOWER then GnuPG (45.19 runs/sec vs 228.68 runs/sec)
ENCRYPT-SMALL-ARMOUR          : RNP is  78% SLOWER then GnuPG (46.18 runs/sec vs 214.35 runs/sec)
#2. Large file symmetric encryption
ENCRYPT-AES128-BINARY         : RNP is  22% SLOWER then GnuPG (231.90 MB/sec vs 295.58 MB/sec)
ENCRYPT-AES192-BINARY         : RNP is  19% SLOWER then GnuPG (216.86 MB/sec vs 268.86 MB/sec)
ENCRYPT-AES256-BINARY         : RNP is  17% SLOWER then GnuPG (204.70 MB/sec vs 247.97 MB/sec)
ENCRYPT-TWOFISH-BINARY        : RNP is  14% SLOWER then GnuPG (109.18 MB/sec vs 127.48 MB/sec)
ENCRYPT-BLOWFISH-BINARY       : RNP is  19% SLOWER then GnuPG (78.65 MB/sec vs 97.26 MB/sec)
ENCRYPT-CAST5-BINARY          : RNP is  17% SLOWER then GnuPG (75.61 MB/sec vs 90.71 MB/sec)
ENCRYPT-CAMELLIA128-BINARY    : RNP is  19% SLOWER then GnuPG (84.15 MB/sec vs 103.85 MB/sec)
ENCRYPT-CAMELLIA192-BINARY    : RNP is  18% SLOWER then GnuPG (69.30 MB/sec vs 84.77 MB/sec)
ENCRYPT-CAMELLIA256-BINARY    : RNP is  18% SLOWER then GnuPG (68.93 MB/sec vs 84.56 MB/sec)
#3. Large file armoured encryption
ENCRYPT-LARGE-ARMOUR          : RNP is  41% FASTER then GnuPG (123.28 MB/sec vs 87.70 MB/sec)
#4. Small file symmetric decryption
DECRYPT-SMALL-BINARY          : RNP is  77% SLOWER then GnuPG (51.85 runs/sec vs 225.28 runs/sec)
DECRYPT-SMALL-ARMOUR          : RNP is  75% SLOWER then GnuPG (51.46 runs/sec vs 204.14 runs/sec)
#5. Large file symmetric decryption
DECRYPT-AES128-BINARY         : RNP is 160% FASTER then GnuPG (306.58 MB/sec vs 118.01 MB/sec)
DECRYPT-AES192-BINARY         : RNP is 153% FASTER then GnuPG (298.43 MB/sec vs 117.88 MB/sec)
DECRYPT-AES256-BINARY         : RNP is 136% FASTER then GnuPG (275.99 MB/sec vs 117.03 MB/sec)
DECRYPT-TWOFISH-BINARY        : RNP is  34% FASTER then GnuPG (113.06 MB/sec vs 84.58 MB/sec)
DECRYPT-BLOWFISH-BINARY       : RNP is   1% FASTER then GnuPG (105.90 MB/sec vs 104.56 MB/sec)
DECRYPT-CAST5-BINARY          : RNP is   0% FASTER then GnuPG (97.26 MB/sec vs 96.95 MB/sec)
DECRYPT-CAMELLIA128-BINARY    : RNP is  17% SLOWER then GnuPG (85.44 MB/sec vs 102.74 MB/sec)
DECRYPT-CAMELLIA192-BINARY    : RNP is  28% SLOWER then GnuPG (70.72 MB/sec vs 98.28 MB/sec)
DECRYPT-CAMELLIA256-BINARY    : RNP is  29% SLOWER then GnuPG (70.36 MB/sec vs 98.98 MB/sec)
#6. Large file armoured decryption
DECRYPT-LARGE-ARMOUR          : RNP is 194% FASTER then GnuPG (127.23 MB/sec vs 43.25 MB/sec)
```

@ni4 Good points - above. Regarding disk - I'm using SSD and i7-4600U CPU @ 2.10GHz. I'll look at it more deeply later today.

**Pull request merged**
