### PR TITLE
Create and use `ax_check_cmocka.m4` #290

### PR DESCRIPTION
**Pull request by ronaldtse**
As title.

### CODE REVIEW

**Comment by flowher** [comment]
So LGTM, but I don't see why it doesn't compile.

**Comment by dewyatt** [comment]
I'll take a look at it

**Comment by ronaldtse** [comment]
Looks like it can't find the cmocka installation on Travis -- happy to hand off to @dewyatt. Thanks!

**Comment by ronaldtse** [comment]
Thanks @dewyatt!

**Pull request merged**
