### PR TITLE
docs: Add missing step for release workflow.

### PR DESCRIPTION
**Pull request by dewyatt**
This step is important to ensure github/`git archive` tarballs are buildable.

I failed to do this for the initial release so we should discuss how to fix that. My thought is to simply amend the commit and move the tag in the release branch, since it's the release itself that is the problem and the code is not changing (so a version bump would be a bit misleading).

### CODE REVIEW

**Comment by ronaldtse** [comment]
Feel free to go ahead to make the commit, it is indeed one issue I encountered in https://github.com/riboseinc/rpm-specs/pull/30

**Comment by dewyatt** [comment]
> Feel free to go ahead to make the commit, it is indeed one issue I encountered in riboseinc/rpm-specs#30

Done (and yes I've been looking at rpm-specs too)

**Comment by dewyatt** [comment]
I went ahead and added the fixed branch naming in here too, as discussed earlier.

**Comment by dewyatt** [comment]
I think I see an ordering issue in these docs, will fix that here or in master later.

**Comment by ronaldtse** [comment]
FYI The RNP yum package is now available on our yum repo for CentOS/RHEL: https://github.com/riboseinc/yum

**Pull request merged**
