### PR TITLE
Cleanup digest code

### PR DESCRIPTION
**Pull request by randombit**
Addressing #106 

Lot of changes in here but nothing too scary. Did not make `pgp_hash_t` completely opaque because some places create `pgp_hash_t` structs on the stack and I didn't want to change them all. However it removes the function pointer members (init, add, finish) and forces all operations to go through functions, instead of accessing any `pgp_hash_t` struct members directly. So opaque in practice at least, and a stepping stone for making the struct fully (actually) opaque.

Another change is removing the (IMO) weird system of calling `pgp_hash_any` then having to call `hash->init` afterwards - now `pgp_hash_create` does both operations. Also removed the algorithm specific constructors (like `pgp_hash_md5`) in favor of `pgp_hash_create(&hash, PGP_HASH_MD5)`

I also removed the `digest_t` wrapper from `rnpv` that was just wrapping `pgp_hash_t`.

Again wrt #101 it doesn't seem like there is any need to split up `hash.c` into multiple files anymore, everything is just handled by a couple of switches. Adding a hash now just means modifying `hash.h` (to add the PGP codepoint to `pgp_hash_alg_t` - I moved this enum from `packet.h`) and then at the top of `hash.c` to add the name.

Oh, git in its infinite wisdom seems to have somehow deduced that I moved `rnpv/digest.h` to `src/lib/hash.h`. In fact `hash.h` was added in the first commit, then `digest.h` deleted later, but I guess they have enough text in common that git decided it was a move, even though the file was added in a commit before the commit where to the 'source' file was removed. So the diff looks weird there. (wtf git)

### CODE REVIEW

**Comment by randombit** [comment]
@dewyatt Yeah that will go away when I fix #114

**Comment by ronaldtse** [comment]
The removal of `hash->init` is extremely welcome and just makes the flow so much easier to understand. Thanks @randombit !

**Comment by ronaldtse** [comment]
@randombit in the changes there are some places where it accounts for undefined SHA-1 and MD5 (via `BOTAN_HAS_x`), but both are "required" in RFC 4880. Maybe we should change it to a switch that if those aren't defined, then rnp should fail outright?

**Comment by randombit** [comment]
@ronaldtse Sounds good I will make a change so configure tests for the essential feature macros (RSA, PKCS1v15 padding, SHA-1, etc) and fails if any are not available in the Botan build.

**Comment by ronaldtse** [comment]
Great plan, thanks @randombit !

**Pull request merged**
