### PR TITLE
ci: Add ruby-rnp HEAD to Cirrus cache fingerprint.

### PR DESCRIPTION
**Pull request by dewyatt**

### CODE REVIEW

**Comment by ronaldtse** [comment]
@dewyatt clever with the fingerprinting 😉

**Comment by dewyatt** [comment]
> @dewyatt clever with the fingerprinting

Maybe too clever, not sure if cirrus will let me install a dep (git) before the fpr script...may have to go with another solution.

**Comment by fkorotkov** [comment]
@dewyatt First of all, nice idea! 🤔 Second, you can put something like that before the cache:

```yaml
install_script: pkg install -y sudo git
dependencies_cache:
  # ...
script: |
  # ...
```

You can have as many [`*_script` instructions](https://cirrus-ci.org/guide/writing-tasks/#script-instruction) as you want.

**Comment by dewyatt** [comment]
Thanks @fkorotkov !

**Comment by ronaldtse** [comment]
CI change, only one approval necessary. Thanks @dewyatt !

**Pull request merged**
