### PR TITLE
Fix bug on test that was found by retrace incompletio

### PR DESCRIPTION
**Pull request by catap**

### CODE REVIEW

**Comment by catap** [comment]
@ni4 good point, thanks!

**Comment by ronaldtse** [comment]
@ni4 are we good to go? Thanks!

**Comment by ni4** [comment]
@ronaldtse Yep, no more comments from my side on this

**Comment by catap** [comment]
@ronaldtse, @dewyatt have you in mind anything to not merge it? :)

**Comment by ronaldtse** [comment]
I thought @flowher would be merging it 😉

**Comment by flowher** [comment]
ups... sorry, I should

**Pull request merged**
