### PR TITLE
Enable AEAD tests against GnuPG

### PR DESCRIPTION
**Pull request by ni4**
This PR should be merged only when https://dev.gnupg.org/T3774 is resolved.
Before that tests could fail randomly.

### CODE REVIEW

**Comment by ronaldtse** [comment]
Thank you @ni4  -- that was really fast 😉 !

**Comment by ronaldtse** [comment]
@ni4 looks like the tests are passing now -- can we merge this? Thanks!

**Comment by ni4** [comment]
@ronaldtse Tests vs GnuPG may fail randomly. GnuPG master still doesn't have fix for the issue.

**Comment by ronaldtse** [comment]
Got it. @ni4 can you track GnuPG's progress and merge when ready? Thanks!

**Comment by ni4** [comment]
@ronaldtse Sure, I'll receive notification on progress on that issue.

**Comment by ni4** [comment]
Closing since it is superseded by #641

**Pull request closed without merging**
