### PR TITLE
Ensure data provided in expert mode key generation are correctly parsed

### PR DESCRIPTION
**Pull request by flowher**
Number of changes here:
1. Code to be tested is in ``rnpkyes`` module. In order to test ``rnpkeys`` it needs to be build to static library that doesn't contain main() function. This patch splits rnpkeys.c in two files.
2. ``rnp_t`` structure contains ``passfp`` field which points to user input stream. Password is not the only input that user provides. Field name is now changed to  ``user_input_fp``. But, I think in the future we should add it to ``pgp_io_t`` and change code accordingly. Also function ``find_passphrase`` requires some changes (see 
#263). I believe both - changes to ``pgp_io_t`` and #263 should be addressed at the same time
3. tui.c: Must read from custom stream, not hardcoded ``stdin``.
4. Finally tests for expert mode were added.

Additionally, I've noticed that calling ``rnp_init`` ``rnp_end`` and again ``rnp_init`` causes segmentation fault as array ``rnp_t::names`` is incorrectly freed/initialized. I didn't investigated this further.

### CODE REVIEW

**Comment by catap** [comment]
> Additionally, I've noticed that calling rnp_init rnp_end and again rnp_init causes segmentation fault as array rnp_t::names is incorrectly freed/initialized. I didn't investigated this further.

I think I fixed it at #259

**Comment by flowher** [comment]
Yes, I've noticed it may be fixed. Havn't tried yet as it wasn't merged when I was working on this PR

**Comment by catap** [comment]
Ok, about `pgp_io_t` and streams. I think we should change the API and provides the way to setup callbacks for interactive interaction with user.

By default we should use current logic with read from `stdio`, but we should provide a way to setup callbacks. And first user of new callback will be our tests :)

@flowher, @ronaldtse what do you think about it?

**Comment by flowher** [comment]
+1. That's how I've imagined this working. Nevertheless, notice that in order to test this functionality, input must be provided from stdin and rnpkeys binary still uses stdin.

**Comment by MohitKumarAgniotri** [comment]
@flowher I will review the changes overnight.

**Comment by ni4** [comment]
Please note that soon we are going to get rid of rnpkeys as a separate utility - all functionality will be merged into one. I will start working on this as soon as my PR is approved and merged. I will merge it after this PR.

Also names/values in rnp_t will be removed, so it's not a problem if something works incorrectly.
Somewhere we agreed on the fact that rnp_io_t should be removed/merged into rnp_ctx_t as well.

**Comment by ni4** [comment]
@catap Agree on the fact that pgp_io_t should be replaced by something callback-based, and be stored in rnp_ctx_t, having initializers for common situations - memory read/write/password request, file read/write/password callback, etc.

**Comment by catap** [comment]
@ni4 and we have this issue: https://github.com/riboseinc/rnp/issues/157

**Comment by flowher** [comment]
@ni4 yes,that's obvious. We don't have it yet, though.

**Comment by flowher** [comment]
@MohitKumarAgniotri @ronaldtse @ni4 @catp Thanks for review and comments !

**Pull request merged**
