### PR TITLE
Fix leaks in rnp_tests and re-enforce sanitize-leaks CI run.

### PR DESCRIPTION
**Pull request by dewyatt**
**Note**: The other PRs I have open should be merged before this one so that we can see the sanitize-leaks CI run pass. (I expect it to fail here initially)

Right now in master `rnp_tests` leaks quite a bit for me:
```SUMMARY: AddressSanitizer: 265317 byte(s) leaked in 1587 allocation(s).```

This, combined with the other PRs, should get us back to 0 so that we can re-enforce the sanitize-leaks CI run. (Hoping to add a valgrind run soon too)

### CODE REVIEW

**Comment by dewyatt** [comment]
I see one thing I'll need to fix here, I'll take a look soon but this is pending the other PRs anyways.

**Comment by dewyatt** [comment]
Ok, fixed the previous issue. CI will fail on the sanitize-leaks runs until the other PRs are merged and I rebase, so we're just waiting on those.

**Comment by dewyatt** [comment]
It looks like there's a few leaks that I somehow missed locally, so I'll continue adding commits to get all them fixed.

@ni4 Can you double-check me on 601c78a0acafb29ddf4c406b952bb3b43e6c4252? The cache is leaked for partial packet sources, I can see multiple ways to fix it, not sure what is most appropriate though.

**Comment by ni4** [comment]
@dewyatt Thanks for noticing this. Fix looks pretty correct to me.

**Comment by dewyatt** [comment]
Ok it sounds like we're good to go then, sanitize-leaks is passing now, permission to merge is granted so I'll go ahead and merge.

Ideally we should rebase all open PRs on master after this to ensure we're not introducing any new leaks.

**Pull request merged**
