### PR TITLE
FFI: add rnp_disable_debug() and allocation check to rnp_set_debug().

### PR DESCRIPTION
**Pull request by ni4**
We need this function to not make Travis sad because of too long logs.
Also it may be found useful in other cases.

### CODE REVIEW

**Comment by ronaldtse** [comment]
@ni4 thanks for this! The only test failure is https://travis-ci.org/riboseinc/rnp/jobs/547794176 where there's an error at:

```
+env CI=false LD_LIBRARY_PATH=/Users/travis/local-installs/botan-install/lib:/Users/travis/local-installs/jsonc-install/lib:/Users/travis/local-installs/rnp-install/lib bundle exec rspec
bundler: command not found: rspec
Install missing gem executables with `bundle install`
/Users/travis/.travis/functions: line 524:  3686 Terminated: 15          travis_jigger "${!}" "${timeout}" "${cmd[@]}"
The command "if [[ ${COVERITY_SCAN_BRANCH} != 1 ]]; then travis_wait 50 ./ci/main.sh; fi" exited with 127.
```

**Comment by ni4** [comment]
@ronaldtse Hm, it should be something with PATH or other environment setup. @dewyatt do you have any idea? Or should I dig into it?

**Comment by dewyatt** [comment]
@ni4 Hmm, I'll take a look.

**Comment by ni4** [comment]
Thanks, @dewyatt !

**Comment by ni4** [comment]
@dewyatt @ronaldtse Could you please approve this? Now it works fine, and want to merge it so other PRs may be quickly rebased and pass Travis.

**Pull request merged**
