### PR TITLE
Add test for validate_key_material() function.

### LINKED ISSUE #880: Add test for elgamal_validate_key
## Description

I'm guessing we should be able to catch this in a test:
https://github.com/riboseinc/rnp/pull/875/files#r305010728

### PR DESCRIPTION
**Pull request by ni4**
This PR improves ECDH key material validation and adds test for key material validation.
Fixes #880

### CODE REVIEW

**Comment by ronaldtse** [comment]
Thanks @ni4! Seems that Cirrus just failed...

**Comment by ni4** [comment]
@ronaldtse Yeah, `FAILED_PRECONDITION: No tasks found to start!!`. 
@dewyatt is this something we should debug, or something being reconfigured now?

**Comment by dewyatt** [comment]
> @ronaldtse Yeah, `FAILED_PRECONDITION: No tasks found to start!!`.
> @dewyatt is this something we should debug, or something being reconfigured now?

Might be a Cirrus CI or GitHub bug, I've seen it once before (I think yesterday when GH was breaking). Anyways, we can see it actually passed so IMO we shouldn't worry about it unless it persists: https://cirrus-ci.com/task/5698445329825792

**Comment by dewyatt** [comment]
I reported the `Cirrus CI` check issue. We can ignore it for now, it's not a failure of our tests.

**Pull request merged**
