### PR TITLE
Memory fuzzying

### PR DESCRIPTION
**Pull request by catap**
First step to run rnp with retrace's memory fuzzing.

### CODE REVIEW

**Comment by ronaldtse** [comment]
@catap this is very nice!

**Comment by catap** [comment]
@ronaldtse I feel that retrace should have a way to switch off retracing and enable only fuzzy, because it produce a lot of garbages.

and I think the right way is create a issue for this :)

**Comment by ronaldtse** [comment]
Agree @catap !

**Comment by ronaldtse** [comment]
@catap these are really good fixes, could we make the build pass so we can merge this soon? Thanks!

**Comment by catap** [comment]
@ronaldtse strange, the 'style check' had failed, but I restarted a job... and it passed.

So, I think we can merge it :)

**Comment by ni4** [comment]
Yeah, please merge so I can apply those changes and finally make PR with refactoring.

**Comment by ronaldtse** [comment]
Thank you guys!!

**Pull request merged**
