### PR TITLE
Update readme with instructions for debian

### PR DESCRIPTION
**Pull request by ni4**
I'm not quite familiar with debian but these instructions at least allows to build on clean debian/stretch Docker container.

Based on #748

### CODE REVIEW

**Comment by dewyatt** [comment]
I think it should also install `git` (before the clone), and `zlib1g-dev`.

**Comment by ni4** [comment]
@dewyatt Thank you. Actually it is a good idea to try those instructions before issuing the PR :) Now it seems to work fine.

**Comment by dewyatt** [comment]
Let's go ahead and merge this since it's just docs. :)

**Comment by ronaldtse** [comment]
Thanks @ni4 @dewyatt ! We really should go ahead with the automated CI build of all sorts of packages...

**Comment by dewyatt** [comment]
> We really should go ahead with the automated CI build of all sorts of packages...

@ronaldtse I'm working on the gitlab ci automation for this sort of stuff but it will be a few more weeks. I'm trying to improve things and take advantage of gitlab ci features and tune things up, etc., rather than do a 1:1 conversion. (I already spent most of last week at the NYC maker faire for my birthday today)

**Pull request merged**
