### PR TITLE
Add FFI examples

### PR DESCRIPTION
**Pull request by ni4**
This PR adds examples of FFI API usage for the main operations: key generation, export, import, loading/saving of keyrings, encryption, decryption, signing and verification.

Also it updates ffi documentation, and fixes some issues which were found during the examples implementation.

### CODE REVIEW

**Comment by hpk42** [comment]
are there also examples for using rnp without dealing with keyrings at all so that all key storage is left to the caller who just loads keys into memory and then uses them for encryption/decryption/signing/verification ?

**Comment by ni4** [comment]
@hpk42 yeah, please see the verify example. It shows how to use custom key provider. It would be (almost) the same for encryption/decryption/signing.

**Comment by ni4** [comment]
Argh, looks like I broke something in JSON key generation. Will check it tomorrow.

**Comment by ronaldtse** [comment]
@ni4 this looks really good!

The build is failing at these two places:
* https://travis-ci.org/riboseinc/rnp/jobs/465964310 `BUILD_MODE=coverage RNP_TESTS=cmocka GPG_VERSION=beta`

* https://travis-ci.org/riboseinc/rnp/jobs/465964311 `BUILD_MODE=coverage RNP_TESTS=cli GPG_VERSION=beta`

**Comment by ni4** [comment]
@ronaldtse Thanks, will check now. Seems those are because of switching to C language for examples.

**Comment by ni4** [comment]
JFYI: Somehow Travis hanged (while was showing that all tests are passing) so I restarted the build

**Pull request merged**
