### PR TITLE
Fix errors in key generation tests and some other CLI test improvements

### PR DESCRIPTION
**Pull request by ni4**
This PR:
- fixes gpg key generation test
- reduces number of encryption test runs (we really don't need to run each file size for each algorithm, just need to check all algos/all sizes/all compression algorithm combinations)
- enables debug logging for CI
- fixes buffer underflow in cleartext_process_line (see https://github.com/riboseinc/rnp/pull/581#issuecomment-360343555)

### CODE REVIEW

**Comment by ronaldtse** [comment]
Thanks @ni4! Somehow Travis is still failing with this:

```
======================================================================
ERROR: test_generate_key_with_gpg_import_to_rnp (__main__.Keystore)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "cli_tests.py", line 691, in test_generate_key_with_gpg_import_to_rnp
    raise_err('gpg key generation failed, error ' + str(ret) , err)
  File "/home/travis/build/riboseinc/rnp/src/tests/cli_common.py", line 22, in raise_err
    raise CLIError(msg, log)
CLIError: None

----------------------------------------------------------------------
Ran 21 tests in 278.324s

FAILED (errors=1)
```

**Comment by ni4** [comment]
@ronaldtse Arggh, this will never end :) Still failure in miscommunication with gpg-agent, will fix it.

**Comment by dewyatt** [comment]
@ronaldtse What happened with the macos jenkins run?

Assuming that is OK, I think this PR is fine as a stopgap measure.

**Comment by ronaldtse** [comment]
@dewyatt the build actually succeeded but the slave got disconnected due to network issues. It's a pass 😉

**Comment by ronaldtse** [comment]
Would the second reviewer please merge this? Thanks!

**Pull request merged**
