### PR TITLE
Convert from OpenSSL to Botan for crypto operations

### PR DESCRIPTION
**Pull request by randombit**
Fixing #8 

This replaces all OpenSSL usage with the Botan crypto library, using Botan's C API. The very latest version (2.1.0) is required. This took me a while and my commit history was a mess, so I restaged everything and recommitted in a somewhat logical order, which is why all of the commits are from this afternoon.

This PR needs more testing, but I think it is ready for a first review.

Some possible further improvements, which I am not going to try addressing in this PR:

- rnp rolls its own PKCSv1.5 encoding code and then uses OpenSSL's RSA_NO_PADDING (or now Botan's equivalent "Raw"). Instead rnp should use the library version of the padding operations. This will probably require some significant changes because rnp also wants to compute the signature digests itself, and it seems like in some cases the packet parsing code and digest update code are somewhat intertwined. rnp's requirement for message recovery on RSA signatures (RSA_public_decrypt in OpenSSL land) is not available through the Botan signature API. The message encryption case is probably easier to tackle.
- rnp implements ElGamal using OpenSSL's BN API, since it is not supported by OpenSSL. Botan already includes it.

### CODE REVIEW

**Comment by ronaldtse** [comment]
Thank you @randombit , let me move the pending TODOs to new issues, and let's get this tested first -- if we had tests it would have been much easier!

**Comment by randombit** [comment]
I'm working on crypto unit tests (using cmocka - https://cmocka.org/) in a new branch, which allows me to run the same tests against both openssl and botan versions of the lib. That has already found one issue in CFB cipher handling that I'm debugging now, so this PR should certainly not be merged yet.

**Comment by shaunwheelhouse** [comment]
@ronaldtse, @randombit - I'm so sorry that I didn't get to this earlier! I didn't receive a notification!

Testing master is going to be very difficult because the --homedir functionality is broken and the holdover fixes are in the name_refactor_wip branch. We should get that branch completed and merged ASAP so that good work like this can be assessed on a stable base.

**Comment by ronaldtse** [comment]
@randombit @shaunwheelhouse I've updated dependency building to include packages required by `botan`/`cmocka` and also updated the README to reflect latest build procedures.

Perhaps we will want to make `automake` handle these dependencies directly later.

**Comment by ronaldtse** [comment]
@shaunwheelhouse I've merged the latest changes from master.

**Comment by randombit** [comment]
@shaunwheelhouse  Thanks I'll take a look at the problem you mention sometime today

**Comment by randombit** [comment]
@shaunwheelhouse Hi Shaun both bugs should be fixed now in f04e8dd let me know what you think. Thanks!

**Comment by ronaldtse** [comment]
@shaunwheelhouse feel free to merge once it is good. Thanks!

**Comment by shaunwheelhouse** [comment]
@randombit - Your changes are great, thanks for fixing those issues. :+1:

@randombit, @ronaldtse - Sorry again for the late attention! Now that the easter holidays are over I'll be more responsive. 🔧

**Comment by ronaldtse** [comment]
Thank you @shaunwheelhouse and @randombit !!

**Pull request merged**
