### PR TITLE
Abstract keyring

### PR DESCRIPTION
**Pull request by catap**
Made keyring as abstract (right now is SSH or GPG backend but easy to add KBX format) for #33 .

### CODE REVIEW

**Comment by ronaldtse** [comment]
Thanks @catap , great first step for keybox. It's quite a huge change -- @dewyatt and @randombit would you have time to review this?

**Comment by catap** [comment]
@ronaldtse I've tried split it to many commits to make review as easy as I can. Meanwhile a lot of code just moved from one files to another.

**Comment by ronaldtse** [comment]
@catap one thing I noticed is that the name "Keyring" is OpenPGP 4880 specific.

* the term in SSH is called "Keychain" (keys in the `~/.ssh` directory)
* later on we will have "Keybox"

It would be better if we start using a prefix "`key_container_`" or "`key_store_`" or "`key_store_`" to differentiate between all these terms.

**Comment by catap** [comment]
@ronaldtse, agre and I think that's using `rnp_key_store` is good.

Meanwhile, I'm waiting feedback from @randombit and @dewyatt, because one more rename will made review much more terrible ;)

**Comment by ronaldtse** [comment]
Thanks @catap 👍

**Comment by dewyatt** [comment]
I don't think `pgp_export_key` should live in `packet-print.c` but that's a minor thing, so let's merge.

**Pull request merged**
