### PR TITLE
Fixes for armor and cleartext messages parsing

### PR DESCRIPTION
**Pull request by ni4**
Sorry for putting a bit different things into the single pull request. 
So this one:
- fixes misc armoring/dearmoring processing problems
- fixes partial data length processing in dearmoring code
- fixed cleartext signing/verification
- adds CLI tests for armored and cleartext stuff

### CODE REVIEW

**Comment by ronaldtse** [comment]
@ni4 I feel that the characters like `"- "` and `'\n'` should be assigned by some definition.

**Comment by catap** [comment]
Looks good but I agree with @ronaldtse remarks about `"- "`.

**Comment by ni4** [comment]
@ronaldtse @catap Thanks, you are right. Will update PR with defines

**Comment by ni4** [comment]
@ronaldtse  @catap Done. If somebody have idea of better place for those defines (so we can use them from repgp/reader.c) you are welcome to share.

**Comment by ronaldtse** [comment]
LGTM, yet one of the CLI tests are failing due to GnuPG problem... can it be fixed?

**Comment by ni4** [comment]
@ronaldtse Sorry, only now found your message. Sure, I remember about this issue and will fix in one of the subsequent PRs with CLI tests update.

**Pull request merged**
