### PR TITLE
JSON output for packet dumper and FFI packet dump

### PR DESCRIPTION
**Pull request by ni4**
This PR adds option to output JSON while dumping packets.
Also it adds functions `rnp_key_packets_to_json` and `rnp_dump_packets_to_json` to the FFI.
First one was needed for CLI, second one will be handy as well in some cases (like tests).

Tests are basic for now since most likely there would be suggestions on JSON structure.
Here are output examples:

<details><summary>Key</summary>

```json
[
  {
    "header":{
      "offset":0,
      "tag":6,
      "tag.str":"Public Key",
      "hdr":"99032e",
      "length":814,
      "partial":false,
      "indeterminate":false
    },
    "version":4,
    "creation time":1522761670,
    "algorithm":17,
    "algorithm.str":"DSA",
    "material":{
      "p.bits":2048,
      "q.bits":256,
      "g.bits":2047,
      "y.bits":2044
    },
    "keyid":"c8a10a7d78273e10"
  },
  {
    "header":{
      "offset":817,
      "tag":13,
      "tag.str":"User ID",
      "hdr":"b406",
      "length":6,
      "partial":false,
      "indeterminate":false
    },
    "userid":"dsa-eg"
  },
  {
    "header":{
      "offset":825,
      "tag":2,
      "tag.str":"Signature",
      "hdr":"8894",
      "length":148,
      "partial":false,
      "indeterminate":false
    },
    "version":4,
    "type":19,
    "type.str":"Positive User ID certification",
    "algorithm":17,
    "algorithm.str":"DSA",
    "hash algorithm":8,
    "hash algorithm.str":"SHA256",
    "subpackets":[
      {
        "type":27,
        "type.str":"key flags",
        "length":1,
        "hashed":true,
        "critical":false,
        "flags":3,
        "flags.str":[
          "certify",
          "sign"
        ]
      },
      {
        "type":11,
        "type.str":"preferred symmetric algorithms",
        "length":4,
        "hashed":true,
        "critical":false,
        "algorithms":[
          9,
          8,
          7,
          2
        ],
        "algorithms.str":[
          "AES-256",
          "AES-192",
          "AES-128",
          "TripleDES"
        ]
      },
      {
        "type":34,
        "type.str":"preferred AEAD algorithms",
        "length":2,
        "hashed":true,
        "critical":false,
        "algorithms":[
          2,
          1
        ],
        "algorithms.str":[
          "OCB",
          "EAX"
        ]
      },
      {
        "type":21,
        "type.str":"preferred hash algorithms",
        "length":5,
        "hashed":true,
        "critical":false,
        "algorithms":[
          10,
          9,
          8,
          11,
          2
        ],
        "algorithms.str":[
          "SHA512",
          "SHA384",
          "SHA256",
          "SHA224",
          "SHA1"
        ]
      },
      {
        "type":22,
        "type.str":"preferred compression algorithms",
        "length":3,
        "hashed":true,
        "critical":false,
        "algorithms":[
          2,
          3,
          1
        ],
        "algorithms.str":[
          "ZLib",
          "BZip2",
          "ZIP"
        ]
      },
      {
        "type":30,
        "type.str":"features",
        "length":1,
        "hashed":true,
        "critical":false,
        "mdc":true,
        "aead":true,
        "v5 keys":false
      },
      {
        "type":23,
        "type.str":"key server preferences",
        "length":1,
        "hashed":true,
        "critical":false,
        "no-modify":true
      },
      {
        "type":33,
        "type.str":"issuer fingerprint",
        "length":21,
        "hashed":true,
        "critical":false,
        "fingerprint":"091c44ce9cfbc3ff7ec7a64dc8a10a7d78273e10"
      },
      {
        "type":2,
        "type.str":"signature creation time",
        "length":4,
        "hashed":true,
        "critical":false,
        "creation time":1549119339
      },
      {
        "type":16,
        "type.str":"issuer key ID",
        "length":8,
        "hashed":false,
        "critical":false,
        "issuer keyid":"c8a10a7d78273e10"
      }
    ],
    "lbits":"0192",
    "material":{
      "r.bits":251,
      "s.bits":256
    }
  },
  {
    "header":{
      "offset":975,
      "tag":14,
      "tag.str":"Public Subkey",
      "hdr":"b9030d",
      "length":781,
      "partial":false,
      "indeterminate":false
    },
    "version":4,
    "creation time":1522761670,
    "algorithm":16,
    "algorithm.str":"Elgamal (Encrypt-Only)",
    "material":{
      "p.bits":3072,
      "g.bits":3,
      "y.bits":3070
    },
    "keyid":"02a5715c3537717e"
  },
  {
    "header":{
      "offset":1759,
      "tag":2,
      "tag.str":"Signature",
      "hdr":"8878",
      "length":120,
      "partial":false,
      "indeterminate":false
    },
    "version":4,
    "type":24,
    "type.str":"Subkey Binding Signature",
    "algorithm":17,
    "algorithm.str":"DSA",
    "hash algorithm":8,
    "hash algorithm.str":"SHA256",
    "subpackets":[
      {
        "type":27,
        "type.str":"key flags",
        "length":1,
        "hashed":true,
        "critical":false,
        "flags":12,
        "flags.str":[
          "encrypt_comm",
          "encrypt_storage"
        ]
      },
      {
        "type":33,
        "type.str":"issuer fingerprint",
        "length":21,
        "hashed":true,
        "critical":false,
        "fingerprint":"091c44ce9cfbc3ff7ec7a64dc8a10a7d78273e10"
      },
      {
        "type":2,
        "type.str":"signature creation time",
        "length":4,
        "hashed":true,
        "critical":false,
        "creation time":1549119406
      },
      {
        "type":16,
        "type.str":"issuer key ID",
        "length":8,
        "hashed":false,
        "critical":false,
        "issuer keyid":"c8a10a7d78273e10"
      }
    ],
    "lbits":"844d",
    "material":{
      "r.bits":256,
      "s.bits":253
    }
  }
]
```
</details>

<details><summary>Signed data</summary>

```json
[
  {
    "header":{
      "offset":0,
      "tag":8,
      "tag.str":"Compressed Data",
      "hdr":"c8ed",
      "partial":true,
      "indeterminate":false
    },
    "algorithm":1,
    "algorithm.str":"ZIP",
    "contents":[
      {
        "header":{
          "offset":0,
          "tag":4,
          "tag.str":"One-Pass Signature",
          "hdr":"c40d",
          "length":13,
          "partial":false,
          "indeterminate":false
        },
        "version":3,
        "type":0,
        "type.str":"Signature of a binary document",
        "hash algorithm":8,
        "hash algorithm.str":"SHA256",
        "public key algorithm":17,
        "public key algorithm.str":"DSA",
        "signer":"2fcadf05ffa501bb",
        "nested":true
      },
      {
        "header":{
          "offset":15,
          "tag":11,
          "tag.str":"Literal Data",
          "hdr":"cbed",
          "partial":true,
          "indeterminate":false
        },
        "format":"b",
        "filename":"128mb.dat",
        "timestamp":1524934672,
        "datalen":134217728
      },
      {
        "header":{
          "offset":134234144,
          "tag":2,
          "tag.str":"Signature",
          "hdr":"c263",
          "length":99,
          "partial":false,
          "indeterminate":false
        },
        "version":4,
        "type":0,
        "type.str":"Signature of a binary document",
        "algorithm":17,
        "algorithm.str":"DSA",
        "hash algorithm":8,
        "hash algorithm.str":"SHA256",
        "subpackets":[
          {
            "type":33,
            "type.str":"issuer fingerprint",
            "length":21,
            "hashed":true,
            "critical":false,
            "fingerprint":"be1c4ab951f4c2f6b604c7f82fcadf05ffa501bb"
          },
          {
            "type":2,
            "type.str":"signature creation time",
            "length":4,
            "hashed":true,
            "critical":false,
            "creation time":1524934948
          },
          {
            "type":3,
            "type.str":"signature expiration time",
            "length":4,
            "hashed":true,
            "critical":false,
            "expiration time":0
          },
          {
            "type":16,
            "type.str":"issuer key ID",
            "length":8,
            "hashed":false,
            "critical":false,
            "issuer keyid":"2fcadf05ffa501bb"
          }
        ],
        "lbits":"b9a8",
        "material":{
          "r.bits":159,
          "s.bits":157
        }
      }
    ]
  }
]
```
</summary>

### CODE REVIEW

**Comment by dewyatt** [comment]
@ni4 For the CI failures, json-c 0.12 and older has a void return for `json_object_object_add` (0.13+ has int). So to be compatible we kind of have to assume void.

**Comment by ni4** [comment]
@dewyatt Thanks, fixed. Let's see if it will go well now (for me local tests are running around an hour with high CPU load so leaving this job to Travis).

**Comment by dewyatt** [comment]
With `RNP_JSON_DUMP_RAW`, what about using `raw` instead of `contents` as the json key? And maybe even for the MPIs (`n.raw` instead of `n.data`). What do you think?

**Comment by ni4** [comment]
@dewyatt Yeah, agree. This makes sense. Any other suggestions?

**Pull request merged**
