### PR TITLE
Add rnp_unload_keys function to the FFI.

### PR DESCRIPTION
**Pull request by ni4**
We didn't have such function before, and it is useful sometimes (at least need this for CLI to FFI transition).

### CODE REVIEW

**Comment by dewyatt** [comment]
Any thoughts on calling it `rnp_unload_keys`? `rnp_clear_keys` might be slightly ambiguous -- when I first read the name I thought it was zeroing key material or something.

**Comment by ni4** [comment]
@dewyatt Yeah, thanks. Don't really like _clear_keys but was not able to find better alternative.

What do you think about the flags?
As I just remembered, we have `RNP_KEY_REMOVE_PUBLIC`/`RNP_KEY_REMOVE_SECRET` constants as well. 
Or would it be better to add `RNP_KEY_UNLOAD_*` ones?

**Comment by dewyatt** [comment]
> @dewyatt Yeah, thanks. Don't really like _clear_keys but was not able to find better alternative.
> 
> What do you think about the flags?
> As I just remembered, we have `RNP_KEY_REMOVE_PUBLIC`/`RNP_KEY_REMOVE_SECRET` constants as well.
> Or would it be better to add `RNP_KEY_UNLOAD_*` ones?

Oh yeah I would probably create new `RNP_KEY_UNLOAD_*` ones, that's what users will likely search for after seeing the rest of the API.

(We probably should have created some generic ones but at this point we would break backwards-compat.)

**Comment by ni4** [comment]
@dewyatt Ok, will update the PR a bit later.

**Comment by ni4** [comment]
@dewyatt Please see the updated PR.

**Pull request merged**
