### PR TITLE
Test cases export key

### PR DESCRIPTION
**Pull request by MohitKumarAgniotri**

### CODE REVIEW

**Comment by ronaldtse** [comment]
@MohitKumarAgniotri I'm getting a segfault with this particular test.

```
[ RUN      ] rnpkeys_exportkey_verifyUserId
[  ERROR   ] --- Test failed with exception: Segmentation fault(11)
[  FAILED  ] rnpkeys_exportkey_verifyUserId
```

Could you help see if it can be fixed? Thanks!

**Comment by MohitKumarAgniotri** [comment]
@ronaldtse Let me have a look. Is this happening with the update for the home dir and keyring fixes?

**Comment by ronaldtse** [comment]
@MohitKumarAgniotri I haven't merged the homedir/keyring fixes yet.

**Comment by MohitKumarAgniotri** [comment]
@ronaldtse I am unable to reproduce the same error. Would it be possible for you to share the backtrace or git-commit hash?

**Pull request merged**
