### PR TITLE
Add support for SM3 hash function

### PR DESCRIPTION
**Pull request by randombit**
GH #55. Currently uses a hash id in the private range (105).

### CODE REVIEW

**Comment by ronaldtse** [comment]
@randombit do we need to also update the `pgp_is_hash_alg_supported` function? I did some initial tracing it seems that this function is only used in `process_dash_escaped`, but `process_dash_escaped` doesn't even seem used anywhere. If that's the case could we remove both unused functions too? Thanks!

**Comment by dewyatt** [comment]
`process_dash_escaped` is used in reader.c for reading clearsigned messages, so `pgp_is_hash_alg_supported` probably does need some updates.

**Comment by ronaldtse** [comment]
My bad about thinking `process_dash_escaped` isn't used. I need better eyes. Look forward to the updates.

**Comment by ronaldtse** [comment]
Speaking of support within `pgp_is_hash_alg_supported`, it only returns `1` on:

``` c
PGP_HASH_MD5
PGP_HASH_SHA1
PGP_HASH_SHA256
```

But not for these:
``` c
PGP_HASH_SHA512
PGP_HASH_SHA384
```

We should add those in as well. Maybe there is a better way indicating supported hash functions instead of having these constants littered in multiple places?

**Comment by randombit** [comment]
@ronaldtse Suggested changes all sound good. On another project tomorrow, but should have updates to this PR later in the week.

The current sign+verify test doesn't test clearsigned messages because while `rnp_sign_memory` can create one, I could not figure out how to verify a clearsigned message using `rnp_verify_memory` - hints welcome.

**Comment by dewyatt** [comment]
> I could not figure out how to verify a clearsigned message using rnp_verify_memory - hints welcome.

It looks like clearsign verification with `rnp_verify_memory` doesn't work right now, so I'll create an issue. I recall the clearsign functionality was originally incomplete upstream so I did some work on that for signing (435f9fbd2fcba73e95eab884f150729efde28694) but not verifying.

`rnp_verify_file` can, however, verify clearsign messages.

**Comment by dewyatt** [comment]
@randombit Wait...I think I'm wrong on that. I think you should currently be able to verify clearsigned messages with rnp_verify_memory. I'll get back to you on that.

**Comment by dewyatt** [comment]
@randombit Ok `rnp_verify_memory` will indeed verify clearsign messages. I suspect you may have had trouble because you were including the null terminator in the signature payload. Something like this would work for testing clearsign:
https://gist.github.com/dewyatt/b9dd6cb8127056ec8bfddd830de76689

(and `pgp_is_hash_alg_supported` would indeed need to be expanded to support the other hashes in the current test.)

I'll file an issue to discuss whether there is a bug here (don't want to derail this PR).

**Comment by dewyatt** [comment]
@randombit Hmm, actually maybe it's just my lack of sleep. It should verify fine with the NULL terminator as well. Just make sure `armored=1` and that you stick to hashes that `pgp_is_hash_alg_supported` currently likes. I do wonder if `pgp_sign_buf` should explicitly fail when `cleartext=1` and a null byte is in the data, but that's a separate discussion.

**Comment by randombit** [comment]
@dewyatt Am I right in thinking that if clearsigned=1 and armored=0, nothing useful happens? `rnp_sign_memory` succeeds, but I can't get the output to verify and it doesn't seem like the combination makes sense since clearsigned is for plaintext transport/display. Should `rnp_sign_memory` (or some lower-level function down the call stack) fail when clearsigned=1,armored=0 combination is used?

**Comment by dewyatt** [comment]
@randombit It looks like `pgp_sign_buf` completely ignores `armored` when `cleartext=1`. So it would probably produce valid armored output, but then you try to verify it as non-armored.

So I think we should have `pgp_sign_buf` fail with that combination of arguments as it's pretty misleading. Same thing for `pgp_sign_file`.

**Comment by dewyatt** [comment]
Also, I noticed GnuPG does allow NULL bytes in clearsign messages, and they verify fine, etc. Seems weird, but I guess it's OK.

I think the remaining task here is updating `pgp_str_to_hash_alg`.
I think we need to have the tests check the return value of rnp_setvar for "hash" since it does fail: https://github.com/riboseinc/rnp/blob/2d21450e8f5601da0f203507966c3a7308469bd3/src/lib/rnp.c#L2181

**Comment by randombit** [comment]
@dewyatt SM3 was already in `pgp_str_to_hash_alg` but I enabled SHA-224 while in there. RIPEMD-160 is not supported by hash.c at all right now so I disabled the attempt to test it in `rnpkeys_generatekey_verifySupportedHashAlg`

**Comment by dewyatt** [comment]
@randombit That makes sense. Ready for merge?

**Comment by randombit** [comment]
Yes I think all ready here

**Pull request merged**
