### PR TITLE
Removes memory leaks from rnpkeys

### PR DESCRIPTION
**Pull request by flowher**
* Removes memory leaks from rnpkeys that occur on key generation
* Makes set_core_dumps more readable

### CODE REVIEW

**Comment by ronaldtse** [comment]
Looks great. Thanks @flowher for the fix!

**Comment by ronaldtse** [comment]
It looks like places like write_seckey_body still have hard coded key lengths for CAST. We should make a new issue to clean them up all at once.

**Comment by randombit** [comment]
@ronaldtse All of those cases are resolved in #140

**Comment by ronaldtse** [comment]
Got it, thanks @randombit !

**Pull request merged**
